pipeline:
  name: mac
  identifier: mac
  projectIdentifier: pranavt1
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: pranavgithub
        repoName: Bitrise-iOS-Cocoapods-Sample
        build: <+input>
  stages:
    - stage:
        name: build
        identifier: build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: MacOS
            arch: Arm64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: hello
                  identifier: hello
                  spec:
                    shell: Sh
                    command: |-
                      echo hello
                      xcodebuild -list
                      xcodebuild clean test
                      scheme_list=$(xcodebuild -list -json | tr -d "\n")
                      default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
                      echo $default | cat > default
                      echo Using default scheme: $default
                      if [ $scheme = default ]; then scheme=$(cat default); fi
                      if [ "`ls -A | grep -i \\.xcworkspace\$`" ]; then filetype_parameter="workspace" && file_to_build="`ls -A | grep -i \\.xcworkspace\$`"; else filetype_parameter="project" && file_to_build="`ls -A | grep -i \\.xcodeproj\$`"; fi
                      file_to_build=`echo $file_to_build | awk '{$1=$1;print}'`
                      xcodebuild clean build
